# Generated by Django 5.2.4 on 2025-07-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used - Like new', 'Used - Like new'), ('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair')], default='New', max_length=20),
        ),
    ]
