# Generated by Django 5.2.4 on 2025-07-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_options_remove_item_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='Cairo, Egypt', help_text='City, Country (e.g., Cairo, Egypt)', max_length=255),
        ),
    ]
