# Generated by Django 5.2.4 on 2025-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(default='Cairo, Egypt', max_length=255),
        ),
    ]
